### ISSUE TITLE
libnd4j uses anacoda's MKL libs after build

### ISSUE THREAD

**Issue by ds923y** [deeplearning4j/libnd4j#152]
### Env

0.4-rc3.9-SNAPSHOT
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
**OS name: "mac os x", version: "10.11.4", arch: "x86_64", family: "mac"**
**Python 2.7.11 :: Anaconda 4.0.0 (x86_64)**
Install the python anaconda distribution
### To Reproduce
1. Install anaconda
2. cd ~
3. git clone https://github.com/deeplearning4j/libnd4j.git
4. follow instructions in macOSx10 (CPU only).me
5. Install Canova
6. Install Nd4j with `mvn clean install -X -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda 7.5'`
7. Install Deeplearning4j
8. Run examples
9. `cd ~`
10.  `git clone https://github.com/deeplearning4j/dl4j-0.4-examples.git`
11. `cd dl4j-0.4-examples`
12.  `mvn package`
13. `java -cp target/deeplearning4j-examples-0.4-rc0-SNAPSHOT-bin.jar org.deeplearning4j.examples.recurrent.character.GravesLSTMCharModellingExample`
14. observe **actual output**
15. move the anaconda2 folder from the home folder to the Desktop
16. repeat build steps and observe **expected output**
###### Expected:

java -cp target/deeplearning4j-examples-0.4-rc0-SNAPSHOT-bin.jar org.deeplearning4j.examples.recurrent.character.GravesLSTMCharModellingExample
Using existing text file at /var/folders/tv/klm99r2s62x6kh28p956g6xw0000gn/T/Shakespeare.txt
Loaded and converted file: 5459809 valid characters of 5465100 total characters (5291 removed)
Number of parameters in layer 0: 223000
Number of parameters in layer 1: 321400
Number of parameters in layer 2: 15477
Total number of network parameters: 559877
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 217.19934415874616
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 215.8755465108869
###### Actual:

java -Djava.library.path=/Users/administrator/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/  -cp target/deeplearning4j-examples-0.4-rc0-SNAPSHOT-bin.jar org.deeplearning4j.examples.recurrent.character.GravesLSTMCharModellingExample
Using existing text file at /var/folders/tv/klm99r2s62x6kh28p956g6xw0000gn/T/Shakespeare.txt
Loaded and converted file: 5459809 valid characters of 5465100 total characters (5291 removed)
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/administrator/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjniNativeOps.dylib: dlopen(/Users/administrator/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjniNativeOps.dylib, 1): Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/administrator/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/./libnd4j.dylib
  Reason: image not found
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1855)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:636)
    at org.bytedeco.javacpp.Loader.load(Loader.java:474)
    at org.bytedeco.javacpp.Loader.load(Loader.java:411)
    at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:27)
    at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:27)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4713)
    at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4660)
    at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:146)
    at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:487)
    at org.deeplearning4j.examples.recurrent.character.GravesLSTMCharModellingExample.main(GravesLSTMCharModellingExample.java:73)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/tv/klm99r2s62x6kh28p956g6xw0000gn/T/javacpp177015620156592/libjniNativeOps.dylib: dlopen(/private/var/folders/tv/klm99r2s62x6kh28p956g6xw0000gn/T/javacpp177015620156592/libjniNativeOps.dylib, 1): Library not loaded: libmkl_rt.dylib
  Referenced from: /private/var/folders/tv/klm99r2s62x6kh28p956g6xw0000gn/T/javacpp177015620156592/./libnd4j.dylib
  Reason: image not found
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:619)
    ... 14 more

**Comment by treo** [comment]
That is actually expected behavior. When you build libnd4j, it looks first for Intels MKL, as that usually performs best, and then everything else. If you move MKL away, it will not be able to find it any more.

So if you don't want to use MKL, make sure it isn't on your path while building libnd4j.

**Comment by saudet** [comment]
Well, actually we might want to bundle everything in JAR files, but that becomes hard to do when linking with things here and there, and it doesn't solve conflicts with DLLs on Windows, etc. So, I'm thinking that linking everything statically would fix all that...

**Comment by ds923y** [comment]
If someone really wants to use anaconda's MKL
they can do 
`cp ~/anaconda2/pkgs/mkl-11.3.1-0/lib/* ~/dl4j-0.4-examples`
If another avenue is to edit the file ***libnd4j/cmake/FindBLAS.cmake***
        find_library(${_prefix}_${_library}_LIBRARY
                    NAMES ${_library}
                    PATHS /usr/lib /usr/local/lib64 /usr/lib64 ENV DYLD_LIBRARY_PATH
                    )`
the anaconda libs are found through the PATH variable so modifying the ***find_library*** call can fix this

**Comment by agibsonccc** [comment]
That's REALLY helpful. I will make the associated changes in the CMakeLists.txt

**Comment by saudet** [comment]
libnd4j no longer needs BLAS. ND4J now depends on the build from the JavaCPP Presets for that.
