### ISSUE TITLE
Crash on CPU Backend after some use

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#17]
After learning for about 20 Minutes the JVM crashes.

The following logs show more information about the crash:
[hs_err_pid9620.log.txt](https://github.com/deeplearning4j/libnd4j/files/162122/hs_err_pid9620.log.txt)
[hs_err_pid12076.log.txt](https://github.com/deeplearning4j/libnd4j/files/162123/hs_err_pid12076.log.txt)

**Comment by treo** [comment]
I'm back with some more information and a minimal test case:

```java
import org.nd4j.linalg.factory.Nd4j;

public class App 
{
    public static void main( String[] args )
    {
       Nd4j.ones((1024 * 1024 * 511) + (1024*1024 - 1)); // Still works
       Nd4j.ones((1024 * 1024 * 511) + (1024*1024)); // Crashes
    }
}
```

See the attached log file for the crash log when running this example.
[hs_err_pid1932.log.txt](https://github.com/deeplearning4j/libnd4j/files/163126/hs_err_pid1932.log.txt)

**Comment by treo** [comment]
The current state doesn't crash the JVM on this anymore, but it still results in an exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Negative capacity: -2147483648
	at java.nio.Buffer.<init>(Buffer.java:199)
	at java.nio.ByteBuffer.<init>(ByteBuffer.java:281)
	at java.nio.ByteBuffer.<init>(ByteBuffer.java:289)
	at java.nio.MappedByteBuffer.<init>(MappedByteBuffer.java:89)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:162)
	at org.bytedeco.javacpp.Pointer.asDirectBuffer(Native Method)
	at org.bytedeco.javacpp.Pointer.asByteBuffer(Pointer.java:484)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:536)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:40)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:227)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1155)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1560)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1670)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.ones(BaseNDArrayFactory.java:1249)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.ones(BaseNDArrayFactory.java:995)
	at org.nd4j.linalg.factory.Nd4j.ones(Nd4j.java:4224)
	at com.example.App.main(App.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) 
```

**Comment by saudet** [comment]
It's already in in the `longptr` branch, but I've tried it here, but we end up with another exception:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectFloatBufferU.put(DirectFloatBufferU.java:306)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.put(BaseDataBuffer.java:1067)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.fillPointerWithZero(BaseDataBuffer.java:513)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:548)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:40)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:227)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1155)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1560)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1670)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.ones(BaseNDArrayFactory.java:1249)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.ones(BaseNDArrayFactory.java:995)
	at org.nd4j.linalg.factory.Nd4j.ones(Nd4j.java:4224)
```
I'm afraid we'll need some sort of hack like accessing large arrays using multiple buffers...

**Comment by agibsonccc** [comment]
I'd be ok just restricting using of bytebuffers to 2.1 billion element and forcing javacpp data types for > 2.1 bilion

**Comment by saudet** [comment]
Direct NIO buffers are the most efficient way to access native memory efficiently, though. Unless we can guarantee to never access those regions of memory directly from Java on a per element basis, we're going to need to do something about it.

It's a bit reminiscent of what happens on Android. On that platform, direct NIO buffers are inefficient, so we have to use Java arrays and copy the data back and forth between them and native memory (like we need to do for GPU memory as well). Anyway, I've automated that Java array caching in the indexer package:
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/indexer/Indexer.html
(That also does multidimensional indexing while its at it, but that's not of interest here.)

Since large areas of memory are something that people have to deal with even outside ND4J, I thought maybe that's where we could implement that. We'd have `BigByteBufferIndexer`, etc which would only get created anytime we pass it a Pointer with more elements than only one Buffer can access, so we wouldn't encounter an overhead for smaller number of elements.

**Comment by saudet** [comment]
I've been working on that. The changes I started to make in this branch seem to fix this issue:
https://github.com/deeplearning4j/nd4j/tree/indexer
However, they currently break the allocator in nd4j-cuda-7.5. @raver119 could you take a look? Since you're in the middle of modifying all that, we could start to sync with this I thought.

Moreover, it looks like we're going to need to expand use of `long` to `NDArray`, and that would require adjustments *everywhere* in the code base. So, I'm wondering exactly what actually needs to be upgraded from `int`...

**Comment by agibsonccc** [comment]
Wait...we are going to keep this neutral.  We need to keep using longs for
this. If you have something in particular you are going to do with the
underlying data you can access the address of the array data with
array.data ().address

**Comment by raver119** [comment]
@saudet cuda databuffers aren't ready to any changes yet. i'm yet at the end of rewrite those databuffers to the cuda memory and allocator generalization. Basic tests are passing, but not everything is ready.

Give me some more time please, and we can have longs there. Anyway, there'll be native memory everywhere.

**Comment by saudet** [comment]
@agibsonccc In any case, it's going to require massive changes. But it looks like we can start with the allocator and push the necessary changes from there, so it shouldn't take too long...

@raver119 Sure, just saying we'll need `long` pretty much everywhere. Just keep that in mind. Thanks!

**Comment by raver119** [comment]
@saudet that's np for me, i'm not relying on ints - there's memcpy everywhere

**Comment by treo** [comment]
To update this issue: Using the current master, this works fine and I tried sizes up to Integer.MAX_VALUE.

As ones(int) doesn't take anything larger than that, I started adding dimensions, and there it crashes again with:
```
Exception in thread "main" java.lang.IllegalArgumentException: Length must be >= 1
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:538)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:40)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:227)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1155)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1541)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1651)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.ones(BaseNDArrayFactory.java:1230)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.ones(BaseNDArrayFactory.java:953)
	at org.nd4j.linalg.factory.Nd4j.ones(Nd4j.java:4169)
```

That is using this code:
```java
package com.example;

import org.nd4j.linalg.factory.Nd4j;

public class App {
    public static void main(String... args){
        Nd4j.ones(Integer.MAX_VALUE, 2);
   }
}
```

**Comment by saudet** [comment]
Great, thanks for testing!

Right, so we need to adjust NDArray to use long indexing now. I'll be working on that next, I think, but I'm wondering, do you encounter any issues during actual learning sessions with the way things are right now?

**Comment by treo** [comment]
The original error came up while I was training a rather large network. As I don't have that exact same configuration any more, I'll have to try to remember how it was built, to try if it still happens with the current state. However I'd think that, if nd4j should also be usable as a general purpose library like numpy, a cube of shape (2^10, 2^10, 2^11) shouldn't be too unexpected.

**Comment by saudet** [comment]
I've confirmed that with the commit above the following now works:
```java
        Nd4j.ones(Integer.MAX_VALUE, 2);
        Nd4j.ones(1<<10, 1<<10, 1<<11);
```
which should ideally be included as a unit test, but I'm not sure it's a good idea having unit tests allocating over 8 gigs of RAM just like that...

I think this is about the best we can do without modifying the API of NDArray. And then either we change everything to `long` and break everything, or offer a parallel API with `long[]` parameters, and methods like `rowsLong()`, `shapeLong()`, `lengthLong()`...

**Comment by agibsonccc** [comment]
I'd do that next..

**Comment by treo** [comment]
So I've tried the indexer branch of nd4j on top of current master, and If I use `Nd4j.ones(Integer.MAX_VALUE)` it tells me `Length can not be >= Integer.MAX_VALUE`, if I use one less, then it seems to work.

So I made it larger by adding an additional dimension, and while that doesn't crash, it results in a very wrong result (0) on `Nd4j.ones(Integer.MAX_VALUE -1, 2).sumNumber()` .

**Comment by saudet** [comment]
Right, since the operations are done in libnd4j, we need to "upgrade" that as well. Waiting @agibsonccc comments on that one.

**Comment by agibsonccc** [comment]
Is the nd4j-native-api updated in your branch yet?

**Comment by saudet** [comment]
I haven't touched libnd4j yet, but I've successfully rebased https://github.com/deeplearning4j/nd4j/pull/753 on master

**Comment by agibsonccc** [comment]
@saudet go ahead and go through and update the indexing on there as well

**Comment by saudet** [comment]
Ok, it should be looking pretty good now :) Ops like `Nd4j.ones(1<<10, 1<<10, 1<<11).sumNumber()` work now. Although it doesn't return the "correct" answer, it's not because of long indexing, it's because it's accumulating over single-precision floats. The maximum sum of ones I get with 8 threads is 134217728, but with 1 thread (using `OMP_NUM_THREADS=1`) it's 16777216, which makes sense. But that's a discussion for deeplearning4j/nd4j#733.

@treo In any case, let me know if the PRs looks generally alright and I'll merge this in! Thanks

**Comment by treo** [comment]
The largest array I can try without too much hassle, is 16GB in size, and that worked fine. Also I ran most of the dl4j examples and they seem to work fine for me. So :+1: on merging it :)
