### ISSUE TITLE
No CUDA devices were found in system

### ISSUE THREAD

**Issue by dripp1** [deeplearning4j/libnd4j#211]
When I run:
```
new Word2Vec.Builder()
          .batchSize(WORD_2_VEC_BATCH_SIZE)
          .minWordFrequency(WORD_2_VEC_MIN_WORD_FREQUENCY)
          .useAdaGrad(false)
          .layerSize(WORD_FEATURE_VECTOR_SIZE)
          .iterations(WORD_2_VEC_ITERATIONS)
          .learningRate(WORD_2_VEC_INITIAL_LEARNING_RATE)
          .minLearningRate(WORD_2_VEC_MIN_LEARNING_RATE)
          .negativeSample(WORD_2_VEC_NEGATIVE_WORDS_SAMPLE_SIZE)
          .seed(RANDOM_SEED)
          .windowSize(WORD_2_VEC_WINDOW_SIZE)
          .iterate(lineSentenceIterator)
          .tokenizerFactory(tokenizerFactory)
          .build();
```
I get:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.ExceptionInInitializerError
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:72)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:70)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<clinit>(JCudaExecutioner.java:69)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4743)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4716)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:148)
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable$Builder.<init>(InMemoryLookupTable.java:640)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$Builder.presetTables(SequenceVectors.java:656)
	at org.deeplearning4j.models.word2vec.Word2Vec$Builder.build(Word2Vec.java:426)
	... 5 more
Caused by: java.lang.RuntimeException: No CUDA devices were found in system
	at org.nd4j.jita.conf.Configuration.<init>(Configuration.java:168)
	at org.nd4j.jita.conf.CudaEnvironment.<init>(CudaEnvironment.java:16)
	at org.nd4j.jita.conf.CudaEnvironment.<clinit>(CudaEnvironment.java:11)
	... 28 more
```
I have Nvidia Quadro 600 GPU, and I have installed the NVIDIA CUDA 7.5 toolkit and driver, and verified the installation.
My Gradle dependencies setup is:
   ```
 compile (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '0.4-rc3.9'){ exclude group: 'org.slf4j' }
    compile group: 'org.deeplearning4j', name: 'deeplearning4j-nlp', version: '0.4-rc3.9'
    compile group: 'org.deeplearning4j', name: 'dl4j-spark', version: '0.4-rc3.9'
    compile group: 'org.nd4j', name: 'nd4j-native', version: '0.4-rc3.9'
    compile group: 'org.nd4j', name: 'nd4j-native', version: '0.4-rc3.9', classifier: 'windows-x86_64'
    compile group: 'org.nd4j', name: 'nd4j-cuda-7.5', version: '0.4-rc3.9'
    compile (group: 'org.nd4j', name: 'canova-api', version: '0.0.0.15'){ exclude group: 'org.slf4j' }
    compile (group: 'org.nd4j', name: 'canova-nd4j-codec', version: '0.0.0.15'){ exclude group: 'org.slf4j' }
    compile (group: 'org.bytedeco', name: 'javacpp', version: '1.2'){ exclude group: 'org.slf4j' }
```
What can be wrong here?

**Comment by treo** [comment]
You have 2 problems:
1. At the moment you can't use the CPU and GPU backends together
2. You are missing the dependency line with a classifier for the cuda backend

So remove nd4j-native and add 
`compile group: 'org.nd4j', name: 'nd4j-cuda-7.5', version: '0.4-rc3.9', classifier: 'windows-x86_64'`

**Comment by agibsonccc** [comment]
It also could be the cuda diver not being installed right.

**Comment by dripp1** [comment]
I ran the Nvidia tests and they show that the CUDA driver is installed properly.
I removed the nd4j-native dependency lines  and added the nd4j-cuda backend line, so that my Gradle dependencies now look like this:
```
compile (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '0.4-rc3.9'){ exclude group: 'org.slf4j' }
    compile group: 'org.deeplearning4j', name: 'deeplearning4j-nlp', version: '0.4-rc3.9'
    compile group: 'org.deeplearning4j', name: 'dl4j-spark', version: '0.4-rc3.9'
    compile group: 'org.nd4j', name: 'nd4j-cuda-7.5', version: '0.4-rc3.9'
    compile group: 'org.nd4j', name: 'nd4j-cuda-7.5', version: '0.4-rc3.9', classifier: 'windows-x86_64'
    compile (group: 'org.nd4j', name: 'canova-api', version: '0.0.0.15'){ exclude group: 'org.slf4j' }
    compile (group: 'org.nd4j', name: 'canova-nd4j-codec', version: '0.0.0.15'){ exclude group: 'org.slf4j' }
    compile (group: 'org.bytedeco', name: 'javacpp', version: '1.2'){ exclude group: 'org.slf4j' }
```

but now I get:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:29)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:14)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:9)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<clinit>(JCudaExecutioner.java:67)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4743)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4716)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:148)
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable$Builder.<init>(InMemoryLookupTable.java:640)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$Builder.presetTables(SequenceVectors.java:656)
	at org.deeplearning4j.models.word2vec.Word2Vec$Builder.build(Word2Vec.java:426)
	... 5 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	at org.bytedeco.javacpp.Loader.load(Loader.java:483)
	... 29 more
```

**Comment by agibsonccc** [comment]
Make sure when you run this you set -Djava.library.path="" that's only on
windows you need to do that.

**Comment by dripp1** [comment]
I already have this flag in my VM options, but I still get the above error...

**Comment by saudet** [comment]
Since we're compiling with MSVC 2013, maybe that's what it's looking for:
https://www.microsoft.com/en-us/download/details.aspx?id=40784
If that fixes this issue, I guess we'll bundle those DLLs in the JAR file. Thanks for testing!

**Comment by dripp1** [comment]
So I downloaded and installed the vcredist_x64.exe from that C++ re-distributable, but that did not help
 :-(

**Comment by saudet** [comment]
Could you try to use [Dependency Walker](http://www.dependencywalker.com/) and check which DLL `nd4j.dll` depends on that is missing?

**Comment by dripp1** [comment]
Commenting out the line
`compile (group: 'org.bytedeco', name: 'javacpp', version: '1.2'){ exclude group: 'org.slf4j' }`
in my Gradle dependencies fixed it. Now it works!
