### ISSUE TITLE
Tried running dataproc this happened

### ISSUE THREAD

**Issue by tonythefreedom** [deeplearning4j/libnd4j#225]
I tried to run dl4j-spark-cdh5-examples on google cloud dataproc.
My IDE is intelliJ, build tool is maven.
Exported to jar and uploaded google cloud storage.
Submitted job and this happened.

16/06/01 10:54:32 INFO akka.event.slf4j.Slf4jLogger: Slf4jLogger started
16/06/01 10:54:32 INFO Remoting: Starting remoting
16/06/01 10:54:33 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.140.0.2:33699]
16/06/01 10:54:33 INFO org.spark-project.jetty.server.Server: jetty-8.y.z-SNAPSHOT
16/06/01 10:54:33 INFO org.spark-project.jetty.server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:4040
16/06/01 10:54:33 INFO org.spark-project.jetty.server.Server: jetty-8.y.z-SNAPSHOT
16/06/01 10:54:33 INFO org.spark-project.jetty.server.AbstractConnector: Started SocketConnector@0.0.0.0:37005
16/06/01 10:54:34 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at foodlab-01-m/10.140.0.2:8032
16/06/01 10:54:39 INFO org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Submitted application application_1464763922993_0005
16/06/01 10:54:45 INFO org.deeplearning4j.examples.cnn.MnistExample: Load data....

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:29)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4770)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4716)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:148)
	at org.deeplearning4j.datasets.fetchers.MnistDataFetcher.fetch(MnistDataFetcher.java:137)
	at org.deeplearning4j.datasets.iterator.BaseDatasetIterator.next(BaseDatasetIterator.java:56)
	at org.deeplearning4j.datasets.iterator.BaseDatasetIterator.next(BaseDatasetIterator.java:33)
	at org.deeplearning4j.examples.cnn.MnistExample.main(MnistExample.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.UnsatisfiedLinkError: no nd4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	at org.bytedeco.javacpp.Loader.load(Loader.java:483)
	... 23 more
16/06/01 10:54:46 INFO akka.remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
16/06/01 10:54:46 INFO akka.remote.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
16/06/01 10:54:46 INFO akka.remote.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
Job output is complete

my maven pom is here https://gist.github.com/tonythefreedom/1dfbcf5eb1102337bc59b2666e78a0bd
help me skymind team...

**Comment by saudet** [comment]
Are you making builds on a non-Linux machine?

**Comment by tonythefreedom** [comment]
@saudet yes, I made builds on OSX.

**Comment by saudet** [comment]
Right, so you'll need to add something like this to your pom.xml file:
```
<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>${nd4j.version}</version>
    <classifier>linux-x86_64</classifier>
</dependency>
```
(BTW, until we come up with a more automated solution, this needs to be added to the documentation, somewhere...)

**Comment by tonythefreedom** [comment]
@saudet should I replace <groupId>org.nd4j</groupId> part in my pom to yours? I think I already have linux-x86_64 claasifier in my pom.
`<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>0.4-rc3.9</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>0.4-rc3.9</version>
       </dependency>`

**Comment by agibsonccc** [comment]
You need both declarations.

**Comment by tonythefreedom** [comment]
thanks a lot @agibsonccc

**Comment by tonythefreedom** [comment]
tried with `<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>${nd4j.version}</version>
    <classifier>linux-x86_64</classifier>
</dependency>`

and failed again...

**Comment by saudet** [comment]
What does the output of your build look like? Does it contain that artifact?

**Comment by tonythefreedom** [comment]
I exported it as jar with it.

**Comment by saudet** [comment]
Right, but you shouldn't be getting a "not found" message if it's in the JAR, so my guess is that it's not in the JAR, for some reason.
