### ISSUE TITLE
something wrong for libnd4j  build process on mac osx

### ISSUE THREAD

**Issue by rikima** [deeplearning4j/libnd4j#241]
When libnd4j was built on mac osx and was used in the deeplearning4j developing env. with intellij.
I got errors as follows 

https://gist.github.com/rikima/a745f7639b4dfe97662b971603811f55

a log for libnd4j is as follows
https://gist.github.com/rikima/11d9e9222b32654028fdefd0c6f35784

**Comment by saudet** [comment]
It looks like you've built libnd4j against MKL, but since it's not in your system library path, it can't load it at runtime...

**Comment by rikima** [comment]
I just want to develop dl4j on mac osx.  so, if possible, I dont want to use MKL native library caused error.
are there any workaround?

build process log represents that system can not detect MKL library. 

-- 
-- Could NOT find MKL (missing:  MKL_LIBRARY_DIR LIB_MKL_RT LIB_PTHREAD MKL_INCLUDE_DIR) 
USING BLAS

**Comment by saudet** [comment]
If you just want to use dl4j, don't build from source, just use the binaries.

**Comment by rikima** [comment]
I'd like to develop the dl4j itself. so, I think that I have to get developing env. for dl4j corresponds to the  latest master branch (rc-3.11-SNAPSHOT).

 for this purpose, I dont need to build libnd4j project?

are there any built repository of libnd4j ver. rc-3.11-snapshot?

**Comment by rikima** [comment]
without editing the pom.xml of the dl4j

**Comment by saudet** [comment]
I see. Anyway, it's picking up MKL from somewhere... Are you sure you don't have any libmkl_rt.dylib file anywhere on your system? It seems to be in `/Users/a14350/anaconda/lib/libmkl_rt.dylib`...

**Comment by rikima** [comment]
I got libmkl_rt.dylib in the directory you point out.

----
PC-10671:lib a14350$ ll libmkl_rt.dylib 
-rwxrwxr-x  2 a14350  CATK\Domain Users  11001616 12 24  2015 libmkl_rt.dylib*
PC-10671:lib a14350$ 

Do I have to include above path to the java.library.path in the junit test case option of the dl4j ?

**Comment by saudet** [comment]
I'm not sure that works on Mac OS X. If you want to use it, you'll probably need to add it to the system library path. Then again, maybe it's already in the system library path, and that's why CMake tries to use it, but we cannot actually use that version of MKL outside anaconda for some reason. If that's the case, then make sure libnd4j does not link with it. I'm not sure how to prevent CMake from liking with MKL though...

**Comment by treo** [comment]
@rikima have you tried adding `System.loadLibrary("mkl_rt");` to the beginning of your application? On gitter you only replied that `System.load("mkl_rt")` doesn't work (obviously, as it needs the full path). Please note that there is a difference between the two.

@saudet At least on Windows it is possible to use the MKL shipped with anaconda using the loadLibrary based work around.

**Comment by rikima** [comment]
@treo >have you tried adding System.loadLibrary("mkl_rt"); to the beginning of your application? 
Yes I've tried. 
also, with full path setting, I've tried. 

but  I will try again. 

thanks.

**Comment by rikima** [comment]
@treo 

Thanks for your useful information.

I succeeded to load mkl_rt library below code with -Djava.library.path=/Users/a14350/anaconda/lib/ option.

--
public class App {

    public static void load(String name){
        try{
            System.out.println("Trying to load: "+name);
            System.loadLibrary(name);
        }catch (Throwable e){
            System.out.println("Failed: "+e.getMessage());
            return;
        }
        System.out.println("Success");
    }

    public static void main(String[] args) {
        load("mkl_rt");
    }
}

**Comment by treo** [comment]
Great, now load it before you run into your problem with dl4j.

**Comment by rikima** [comment]
but I couldnt resolve an error on dl4j BaseLayerTest.java ...

- set  -Djava.library.path option
-Djava.library.path=/Users/a14350/anaconda/lib/:/Users/a14350/workspace/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/

- loading mkl native library before Nd4j processing.

public void doBefore(){
        System.out.println("java.library.path: " + System.getProperty("java.library.path"));

        paramTable = new HashMap<>();
        paramTable.put("W", weight);
        paramTable.put("b", bias);

        System.loadLibrary("mkl_rt");

        this.weight =  Nd4j.create(new double[]{0.10, -0.20, -0.15, 0.05},
                new int[]{2, 2});
        this.bias = Nd4j.create(new double[] {0.5,0.5},
                new int[] {1,2});
    }

**Comment by treo** [comment]
Can you please add the error message you are seeing there?

**Comment by rikima** [comment]
error message is similar before.
---
java.lang.UnsatisfiedLinkError: /Users/a14350/workspace/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjnind4j.dylib: dlopen(/Users/a14350/workspace/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjnind4j.dylib, 1): Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/a14350/workspace/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/./libnd4j.dylib
  Reason: image not found

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:702)
	at org.bytedeco.javacpp.Loader.load(Loader.java:500)
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:31)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4902)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4843)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:156)
	at org.deeplearning4j.nn.layers.BaseLayerTest.doBefore(BaseLayerTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.UnsatisfiedLinkError: /Users/a14350/workspace/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjnind4j.dylib: dlopen(/Users/a14350/workspace/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjnind4j.dylib, 1): Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/a14350/workspace/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/./libnd4j.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:685)
	... 39 more

**Comment by saudet** [comment]
In any case, commenting out of `cmake/FindBLAS.cmake` anything related to "mkl" should get you something working, without MKL...

**Comment by rikima** [comment]
I've tried,  but the status is unchanged  ...

What is standard or recommended  developing env. for dl4j in skymind corp.?

windows + intellij or linux + intellij ?

are there any developers with mac osx for dl4j developing in skymind corp. ?

**Comment by saudet** [comment]
Linux + Maven is the basic configuration. Windows and Mac OS X have less capabilities when it comes to debugging native code. Most developers use IntelliJ as IDE, but you have to be careful about that one because it runs on a 32-bit JVM by default, and that's not supported by ND4J. I think pretty much everyone gave us on Mac OS X, given that they don't sell laptops with GPUs from NVIDIA anymore.

**Comment by rikima** [comment]
Thanks for useful info.

I have centos 6.6 server for developing and data processing.  so, for next, I'd like to construct a developing env. on the centos 6.6 with no-gui. 

I'm going to writing code on the mac osx and testing with junit and executing on the centos 6.6

**Comment by saudet** [comment]
But we're still supporting Mac OS X. It's been working fine for everyone that we know of. They just don't usually mess with native code :)

**Comment by rikima** [comment]
...

---
[rikitoku_masaki@... libnd4j]$ ./buildnativeoperations.sh 
eval cmake
PACKAGING = none
BUILD = release
CHIP = cpu
LIBRARY TYPE = dynamic
/home/share/rikitoku_masaki/workspace/libnd4j/blasbuild/cpu
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.2 or higher is required.  You are running version 2.8.12.2

**Comment by saudet** [comment]
We need to install a few things to build on something old like CentOS 6:
```
yum install centos-release-scl-rh epel-release
yum install devtoolset-3-toolchain maven30 cmake3 git openblas-devel
scl enable devtoolset-3 maven30 bash
```

**Comment by rikima** [comment]
@saudet Thanks! 
I colud get cmake 3.2 and gcc 4.9 by same manner which reqired for libnd4j build.

**Comment by rikima** [comment]
On the centos 6.6 with installing cmake 3.2 and gcc 4.9.
I confirmed that junit test cases without some package of the dl4j-core are successfuly executed. 

some test cases have javacpp opencv related process represent errors  related native library. 
they are another problems. so,  in this time, i delete these test cases by hand and execute mvn test.

currently, on the mac osx, it seems that costructing developing env. for dl4j is somewhat difficult.

but,  developing the application using dl4j on the mac osx has no difficulty and no issues.

**Comment by rikima** [comment]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.deeplearning4j.nn.layers.BaseLayerTest
...
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.609 sec - in org.deeplearning4j.nn.layers.BaseLayerTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.123 s
[INFO] Finished at: 2016-06-24T19:39:52+09:00
[INFO] Final Memory: 32M/1233M
[INFO] ------------------------------------------------------------------------
[rikitoku_masaki@... deeplearning4j-core]$

**Comment by rikima** [comment]
Thanks for your suggestions and comments
@treo @saudet

**Comment by agibsonccc** [comment]
Reopening this. We should still note this. I'm also noticing something is consistently wrong with using stuff from acaconda..

**Comment by rikima** [comment]
I'v confirmed that BaseLayerTest.java of latest ver. successfully worked on mac osx without doing any optional setting.
