### ISSUE TITLE
Issues compiling on OSX Sierra - OpenBLAS by default installs gcc6

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/libnd4j#326]
Installed OSX Sierra. Tried to build libnd4j, this is the result: https://gist.github.com/crockpotveggies/a4fea0e8cb89aa9c9373f087f5115c9d

I performed a `brew install openblas` and it installed `gcc6` by default. `gcc5` will compile just fine, but then there's an issue loading OpenBLAS:

```
Caused by: java.lang.UnsatisfiedLinkError: /Users/justin/.javacpp/cache/nd4j-native-0.6.1-SNAPSHOT-macosx-x86_64.jar/org/nd4j/nativeblas/macosx-x86_64/libjnind4j.dylib: dlopen(/Users/justin/.javacpp/cache/nd4j-native-0.6.1-SNAPSHOT-macosx-x86_64.jar/org/nd4j/nativeblas/macosx-x86_64/libjnind4j.dylib, 1): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/openblas/lib/libopenblasp-r0.2.15.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:767)
```

Note that I manually checked and all of the files above are present.

**Comment by saudet** [comment]
Try to build OpenBLAS from source, with this script for example:
https://github.com/bytedeco/javacpp-presets/blob/master/openblas/cppbuild.sh
Or don't use OpenBLAS if you won't need it.

**Comment by saudet** [comment]
It's also possible to compile libnd4j from source with gcc6 :)

**Comment by raver119** [comment]
gcc6 on mac complaints about missing AVX-512 instructions for some reason :(

**Comment by saudet** [comment]
libnd4j no longer needs BLAS. ND4J now depends on the build from the JavaCPP Presets for that.
