### ISSUE TITLE
CUDA Crashes JVM and/or/both Displaydriver

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#39]
Running [MLPMnistSingleLayerExample](https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistSingleLayerExample.java), I've seen serveral different behaviors:

- A JVM Crash: [hs_err_pid10792.log.txt](https://github.com/deeplearning4j/libnd4j/files/180205/hs_err_pid10792.log.txt)
- A Display Driver Crash
- A cudaErrorLaunchFailure:
```
o.d.e.f.m.MLPMnistSingleLayerExample - Build model....
o.n.j.c.CudaEnvironment - Devices found: 1
o.n.j.a.i.AtomicAllocator - Mapping device [0] to thread [1]
o.d.e.f.m.MLPMnistSingleLayerExample - Train model....
Params: gridSize: [1021], blockSize: [768], shMem: [4096]
Params: gridSize: [14], blockSize: [768], shMem: [4096]
Params: gridSize: [1036], blockSize: [768], shMem: [4096]
Params: gridSize: [2], blockSize: [768], shMem: [4096]
[... repeated 68 times ...]
Params: gridSize: [2], blockSize: [768], shMem: [4096]
Params: gridSize: [Exception in thread "main" jcuda.CudaException: cudaErrorLaunchFailure
	at jcuda.runtime.JCuda.checkResult(JCuda.java:435)
	at jcuda.runtime.JCuda.cudaStreamSynchronize(JCuda.java:6661)
	at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:68)
	at org.nd4j.jita.mover.UmaMover.relocate(UmaMover.java:202)
	at org.nd4j.jita.mover.UmaMover.copyback(UmaMover.java:306)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.trySynchronizeHostData(AtomicAllocator.java:735)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.asNio(BaseCudaDataBuffer.java:891)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.sameUnderlyingData(BaseDataBuffer.java:1088)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.doRowWise(BaseNDArray.java:1959)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addiRowVector(BaseNDArray.java:2307)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:327)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:338)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:358)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:520)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:643)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:597)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1715)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1054)
	at org.deeplearning4j.examples.feedforward.mnist.MLPMnistSingleLayerExample.main(MLPMnistSingleLayerExample.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2], blockSize: [768], shMem: [4096]
Params: gridSize: [2], blockSize: [768], shMem: [4096]
[... repeated 53 times ...]
Params: gridSize: [2], blockSize: [768], shMem: [4096]

Process finished with exit code 1
```
- And a different JVM Crash:
```
o.d.e.f.m.MLPMnistSingleLayerExample - Build model....
o.n.j.c.CudaEnvironment - Devices found: 1

Process finished with exit code -1073740940 (0xC0000374)
```

**Comment by raver119** [comment]
99.9% chances this was caused by sgemm. Will sort it out @ morning, and check this usecase once again.
