### ISSUE TITLE
Running Maxout on CUDA crashes the display driver

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#48]
When I run this code, it can crash my display driver quite consistently (when it doesn't crash the jvm first).

```java
package com.example;

import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;

public class CrashMaxout {

    public static void main(String[] args) {
        int size = 12000;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .list(2).layer(0,
                        new DenseLayer.Builder()
                                .nIn(size)
                                .nOut(2500)
                                .activation("maxout")
                                .weightInit(WeightInit.XAVIER)
                                .build())
                        .layer(1,
                        new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                                .nIn(2500)
                                .nOut(250)
                                .weightInit(WeightInit.XAVIER)
                                .activation("sigmoid")
                                .build())
                .backprop(true).pretrain(true)
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(new ScoreIterationListener(1));


        model.fit(new DataSet(Nd4j.create(1, size), Nd4j.create(1, 250)));
    }
}
```

It results in this output:
```
o.d.n.m.MultiLayerNetwork - Training on layer 1 with 12000 examples
o.d.n.m.MultiLayerNetwork - Finetune phase
Exception in thread "main" jcuda.CudaException: cudaErrorLaunchFailure
	at jcuda.runtime.JCuda.checkResult(JCuda.java:435)
	at jcuda.runtime.JCuda.cudaHostAlloc(JCuda.java:3563)
	at org.nd4j.jita.mover.UmaMover.alloc(UmaMover.java:79)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getDevicePointer(AtomicAllocator.java:500)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getDevicePointer(AtomicAllocator.java:622)
	at org.nd4j.linalg.jcublas.CublasPointer.<init>(CublasPointer.java:186)
	at org.nd4j.linalg.jcublas.blas.JcublasLevel3.sgemm(JcublasLevel3.java:52)
	at org.nd4j.linalg.api.blas.impl.BaseLevel3.gemm(BaseLevel3.java:56)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2524)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2333)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:327)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:338)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:358)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:520)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:643)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:597)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:656)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1332)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1386)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1438)
	at com.example.CrashMaxout.main(CrashMaxout.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
CUDA error at C:/Users/dubs/Documents/stuff/clean/libnd4j/blas/cuda/NativeOps.cu:1766 code=4(cudaErrorLaunchFailure) "cudaStreamSynchronize(*stream)" 
```

I've tried to run it with cuda-memcheck, which reported no errors.

**Comment by treo** [comment]
I suspect that this issue is linked to this one: https://github.com/deeplearning4j/libnd4j/issues/53

**Comment by raver119** [comment]
No, its not. CUDA kernels are still in bad state, but https://github.com/deeplearning4j/libnd4j/issues/53 isn't reproducable for me (aka: it works). So for me it sounds like it's something other, system related again.

**Comment by raver119** [comment]
I guess this issue isn't relevant anymore.
