### ISSUE TITLE
Allocating (create) large array crashes (CUDA)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/libnd4j#54]
## Trying to allocate exactly the amount of memory that is available:
```java
package com.example;

import org.nd4j.linalg.factory.Nd4j;

public class App {
    public static void main(String... args){
        Nd4j.create(877306675);
    }
}
```

Output:
```
o.n.j.c.CudaEnvironment - Devices found: 1
o.n.j.c.CudaEnvironment - Device [0]: Free: 3509226700 Total memory: 4294967296
o.n.j.h.i.CudaZeroHandler - Mapping device [0] to thread [1]
o.n.j.a.i.AtomicAllocator - Starting device GC for device: 0
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 0
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 1
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 2
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 3
Exception in thread "main" java.lang.IllegalArgumentException: Negative capacity: -785740596
	at java.nio.Buffer.<init>(Buffer.java:199)
	at java.nio.ByteBuffer.<init>(ByteBuffer.java:281)
	at java.nio.ByteBuffer.<init>(ByteBuffer.java:289)
	at java.nio.MappedByteBuffer.<init>(MappedByteBuffer.java:89)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:162)
	at jcuda.runtime.JCuda.cudaHostAllocNative(Native Method)
	at jcuda.runtime.JCuda.cudaHostAlloc(JCuda.java:3563)
	at org.nd4j.jita.memory.impl.CudaDirectProvider.malloc(CudaDirectProvider.java:37)
	at org.nd4j.jita.memory.impl.CudaCachingProvider.malloc(CudaCachingProvider.java:104)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:145)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:511)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:489)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:146)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:45)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:226)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1155)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:926)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2724)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2592)
```

## Trying to allocate way more memory than is free:
```java
package com.example;

import org.nd4j.linalg.factory.Nd4j;

public class App {
    public static void main(String... args){
        Nd4j.create(Integer.MAX_VALUE);
    }
}
```

Output
```
o.n.j.c.CudaEnvironment - Devices found: 1
o.n.j.c.CudaEnvironment - Device [0]: Free: 3509226700 Total memory: 4294967296
o.n.j.h.i.CudaZeroHandler - Mapping device [0] to thread [1]
o.n.j.a.i.AtomicAllocator - Starting device GC for device: 0
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 0
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 3
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 2
o.n.j.a.i.AtomicAllocator - Starting zero GC for thread: 1
o.n.j.h.i.CudaZeroHandler - No available [HOST] memory, sleeping...
Exception in thread "main" java.lang.IllegalArgumentException: Negative capacity: -4
	at java.nio.Buffer.<init>(Buffer.java:199)
	at java.nio.ByteBuffer.<init>(ByteBuffer.java:281)
	at java.nio.ByteBuffer.<init>(ByteBuffer.java:289)
	at java.nio.MappedByteBuffer.<init>(MappedByteBuffer.java:89)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:162)
	at jcuda.runtime.JCuda.cudaHostAllocNative(Native Method)
	at jcuda.runtime.JCuda.cudaHostAlloc(JCuda.java:3563)
	at org.nd4j.jita.memory.impl.CudaDirectProvider.malloc(CudaDirectProvider.java:37)
	at org.nd4j.jita.memory.impl.CudaCachingProvider.malloc(CudaCachingProvider.java:104)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:145)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:511)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:489)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:146)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:45)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:226)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1155)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:926)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2724)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2592)
```

**Comment by raver119** [comment]
On current master of libnd4j with cherry branch at nd4j this problem isn't an issue anymore. However nd4j cherry branch isn't properly tested yet, and won't be merged today. But that issue is solved there: you can allocate as big buffers as you wish.
