### ISSUE TITLE
conv2d import like this throws npe

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/libnd4j#558]
Python code here:
https://gist.github.com/eraly/dfd994ab778f3b67aa624e486e2040b2

All it does is:
```
imsize = [4, 28, 28, 3]
in0 = tf.placeholder("float", imsize, name="input_0")

filter = tf.Variable(tf.random_normal([5, 5, 3, 3]), name="filterW", dtype=tf.float32)
finish = tf.nn.conv2d(in0, filter, [1, 3, 3, 1], padding='SAME', name="output")
```

Throws a NPE when I try to load the pb.

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/tools.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-backends/nd4j-tests/target/test-classes:/Users/susaneraly/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/susaneraly/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/target/classes:/Users/susaneraly/.m2/repository/com/github/davidmoten/flatbuffers-java/1.7.0.1/flatbuffers-java-1.7.0.1.jar:/Users/susaneraly/.m2/repository/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar:/Users/susaneraly/.m2/repository/guru/nidi/graphviz-java/0.1.4/graphviz-java-0.1.4.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-rasterizer/1.8/batik-rasterizer-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-parser/1.8/batik-parser-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-xml/1.8/batik-xml-1.8.jar:/Users/susaneraly/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-transcoder/1.8/batik-transcoder-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-anim/1.8/batik-anim-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-dom/1.8/batik-dom-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-gvt/1.8/batik-gvt-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-svggen/1.8/batik-svggen-1.8.jar:/Users/susaneraly/.m2/repository/xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-util/1.8/batik-util-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-codec/1.8/batik-codec-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-awt-util/1.8/batik-awt-util-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-bridge/1.8/batik-bridge-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-css/1.8/batik-css-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-ext/1.8/batik-ext-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-script/1.8/batik-script-1.8.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/batik-svg-dom/1.8/batik-svg-dom-1.8.jar:/Users/susaneraly/.m2/repository/xalan/xalan/2.7.0/xalan-2.7.0.jar:/Users/susaneraly/.m2/repository/org/apache/xmlgraphics/xmlgraphics-commons/2.2/xmlgraphics-commons-2.2.jar:/Users/susaneraly/.m2/repository/commons-io/commons-io/1.3.1/commons-io-1.3.1.jar:/Users/susaneraly/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:/Users/susaneraly/.m2/repository/com/eclipsesource/j2v8/j2v8_macosx_x86_64/4.6.0/j2v8_macosx_x86_64-4.6.0.jar:/Users/susaneraly/.m2/repository/com/eclipsesource/j2v8/j2v8_linux_x86_64/4.6.0/j2v8_linux_x86_64-4.6.0.jar:/Users/susaneraly/.m2/repository/com/eclipsesource/j2v8/j2v8_win32_x86_64/4.6.0/j2v8_win32_x86_64-4.6.0.jar:/Users/susaneraly/.m2/repository/uk/com/robust-it/cloning/1.9.3/cloning-1.9.3.jar:/Users/susaneraly/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/Users/susaneraly/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:/Users/susaneraly/.m2/repository/org/projectlombok/lombok/1.16.18/lombok-1.16.18.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-buffer/target/classes:/Users/susaneraly/SKYMIND/nd4j/nd4j-context/target/classes:/Users/susaneraly/SKYMIND/nd4j/nd4j-common/target/classes:/Users/susaneraly/.m2/repository/com/github/stephenc/findbugs/findbugs-annotations/1.3.9-1/findbugs-annotations-1.3.9-1.jar:/Users/susaneraly/.m2/repository/org/apache/commons/commons-math3/3.4.1/commons-math3-3.4.1.jar:/Users/susaneraly/.m2/repository/org/apache/commons/commons-lang3/3.3.1/commons-lang3-3.3.1.jar:/Users/susaneraly/.m2/repository/net/ericaro/neoitertools/1.0.0/neoitertools-1.0.0.jar:/Users/susaneraly/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar:/Users/susaneraly/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar:/Users/susaneraly/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar:/Users/susaneraly/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/target/classes:/Users/susaneraly/.m2/repository/org/bytedeco/javacpp/1.3.4-SNAPSHOT/javacpp-1.3.4-20171113.175342-12.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-serde/nd4j-jackson/target/classes:/Users/susaneraly/SKYMIND/nd4j/nd4j-serde/nd4j-base64/target/classes:/Users/susaneraly/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-shade/jackson/target/classes:/Users/susaneraly/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.5.1/jackson-core-2.5.1.jar:/Users/susaneraly/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.5.1/jackson-databind-2.5.1.jar:/Users/susaneraly/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.5.0/jackson-annotations-2.5.0.jar:/Users/susaneraly/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.5.1/jackson-dataformat-yaml-2.5.1.jar:/Users/susaneraly/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar:/Users/susaneraly/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.5.1/jackson-dataformat-xml-2.5.1.jar:/Users/susaneraly/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/Users/susaneraly/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.5.1/jackson-datatype-joda-2.5.1.jar:/Users/susaneraly/.m2/repository/joda-time/joda-time/2.2/joda-time-2.2.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes:/Users/susaneraly/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.3/openblas-0.2.20-1.3.jar:/Users/susaneraly/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.3/openblas-0.2.20-1.3-macosx-x86_64.jar:/Users/susaneraly/.m2/repository/org/bytedeco/javacpp-presets/mkl/2017.3-1.3/mkl-2017.3-1.3.jar:/Users/susaneraly/.m2/repository/org/bytedeco/javacpp-presets/mkl/2017.3-1.3/mkl-2017.3-1.3-macosx-x86_64.jar:/Users/susaneraly/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar:/Users/susaneraly/.m2/repository/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar:/Users/susaneraly/SKYMIND/nd4j/nd4j-serde/nd4j-camel-routes/nd4j-kafka/target/classes:/Users/susaneraly/.m2/repository/org/apache/camel/camel-kafka/2.16.3/camel-kafka-2.16.3.jar:/Users/susaneraly/.m2/repository/org/apache/camel/camel-core/2.16.3/camel-core-2.16.3.jar:/Users/susaneraly/.m2/repository/org/apache/kafka/kafka_2.11/0.8.2.2/kafka_2.11-0.8.2.2.jar:/Users/susaneraly/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar:/Users/susaneraly/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar:/Users/susaneraly/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.jar:/Users/susaneraly/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.2/scala-parser-combinators_2.11-1.0.2.jar:/Users/susaneraly/.m2/repository/com/101tec/zkclient/0.3/zkclient-0.3.jar:/Users/susaneraly/.m2/repository/log4j/log4j/1.2.14/log4j-1.2.14.jar:/Users/susaneraly/.m2/repository/org/apache/kafka/kafka-clients/0.8.2.2/kafka-clients-0.8.2.2.jar:/Users/susaneraly/.m2/repository/org/xerial/snappy/snappy-java/1.1.1.7/snappy-java-1.1.1.7.jar:/Users/susaneraly/.m2/repository/net/jpountz/lz4/lz4/1.2.0/lz4-1.2.0.jar:/Users/susaneraly/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar:/Users/susaneraly/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar:/Users/susaneraly/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar:/Users/susaneraly/.m2/repository/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.jar:/Users/susaneraly/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar:/Users/susaneraly/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 org.nd4j.imports.TFGraphTestSingle,testOne
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/susaneraly/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/susaneraly/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 4
o.n.n.Nd4jBlas - Number of threads used for BLAS: 4
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [3.6GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
o.n.i.TFGraphTestAll - 
	RUNNING TEST conv_0...
o.n.i.TensorFlowImport - Adding var [input_0:-1]
o.n.i.TensorFlowImport - Adding var [filterW:-2]
o.n.i.TensorFlowImport - Adding op [Identity]
o.n.i.c.TensorFlowMapper - Adding converter for [GenericOpConverter]
o.n.i.c.TensorFlowMapper - Adding converter for [prod]
o.n.i.c.TensorFlowMapper - Adding converter for [pack]
o.n.i.c.TensorFlowMapper - Adding converter for [any]
o.n.i.c.TensorFlowMapper - Adding converter for [lrn]
o.n.i.c.TensorFlowMapper - Adding converter for [stridedslice]
o.n.i.c.TensorFlowMapper - Adding converter for [concat]
o.n.i.c.TensorFlowMapper - Adding converter for [all]
o.n.i.c.TensorFlowMapper - Adding converter for [sum]
o.n.i.c.TensorFlowMapper - Adding converter for [avgpool]
o.n.i.c.TensorFlowMapper - Adding converter for [maxpool]
o.n.i.c.TensorFlowMapper - Adding converter for [mean]
o.n.i.c.TensorFlowMapper - Adding converter for [tensorarraywritev3]
o.n.i.c.TensorFlowMapper - Adding converter for [reshape]
o.n.i.c.TensorFlowMapper - Adding converter for [conv2d]
o.n.i.c.TensorFlowMapper - Adding converter for [stack]
o.n.i.c.TensorFlowMapper - Adding converter for [min]
o.n.i.c.TensorFlowMapper - Adding converter for [max]
o.n.i.c.t.BaseTensorFlowNode - Adding reverse point [filterW/read] -> [1:0]
o.n.i.TensorFlowImport - Node: TNode{inputs=[TIndex{-2:0}], name='filterW/read', id=1, opName='Identity'}
o.n.g.i.TGraph - Adding node by name: [filterW/read]
o.n.i.TensorFlowImport - Adding op [Conv2D]
o.n.i.c.t.BaseTensorFlowNode - Adding reverse point [output] -> [2:0]

java.lang.NullPointerException
	at org.nd4j.imports.converters.tf.Conv2D.asIntermediateRepresentation(Conv2D.java:33)
	at org.nd4j.imports.converters.tf.Conv2D.asIntermediateRepresentation(Conv2D.java:14)
	at org.nd4j.imports.converters.TensorFlowMapper.asIntermediate(TensorFlowMapper.java:66)
	at org.nd4j.imports.TensorFlowImport.importNode(TensorFlowImport.java:532)
	at org.nd4j.imports.TensorFlowImport.traverseList(TensorFlowImport.java:680)
	at org.nd4j.imports.TensorFlowImport.importIntermediate(TensorFlowImport.java:706)
	at org.nd4j.imports.TensorFlowImport.importIntermediate(TensorFlowImport.java:237)
	at org.nd4j.imports.TFGraphTestAll.testSingle(TFGraphTestAll.java:65)
	at org.nd4j.imports.TFGraphTestSingle.testOne(TFGraphTestSingle.java:27)
```

Can be replicated by running the "TFGraphTestSingle" unit test on the eralyTF branch in nd4j. I use libnd4j master

https://github.com/deeplearning4j/nd4j/blob/6fa2507def9138b2c37fef10deadef3bdb960727/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/imports/TFGraphTestSingle.java#L21

**Comment by raver119** [comment]
Should be fixed long ago
