### ISSUE TITLE
Reshape of same shape should not fail

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/libnd4j#652]
o.n.a.s.SameDiff - Action op state is null
o.n.a.s.SameDiff - Executing op mmul
o.n.a.s.SameDiff -  Input shape for x is  [4, 3] Input shape for w is  [3, 1] Output shape for mmul is  [4, 1]
o.n.a.s.SameDiff - Executing op softmax
o.n.a.s.SameDiff -  Input shape for mmul is  [4, 1] Output shape for activation is  [4, 1]
o.n.a.s.SameDiff - Executing op sum
o.n.a.s.SameDiff -  Input shape for activation is  [4, 1] Output shape for totalsum is  [1, 1]
o.n.a.s.SameDiff - Executing op neg
o.n.a.s.SameDiff -  Input shape for totalsum is  [1, 1] Output shape for negtotalsum is  [1, 1]
o.n.a.s.SameDiff - Executing op neg
o.n.a.s.SameDiff -  Input shape for one-var is  [1, 1] Output shape for totalsum-grad is  [1, 1]
o.n.a.s.SameDiff - Executing op tile
o.n.a.s.SameDiff -  Input shape for totalsum-grad is  [1, 1] Output shape for activation-grad is  [4, 1]
o.n.a.s.SameDiff - Executing op _softmaxderivative
o.n.a.s.SameDiff -  Input shape for mmul is  [4, 1] Input shape for activation-grad is  [4, 1] Output shape for mmul-grad is  [4, 1]
o.n.a.s.SameDiff - Executing op mmul
o.n.a.s.SameDiff -  Input shape for mmul-grad is  [4, 1] Input shape for w is  [3, 1] Output shape for mmul_1 is  [4, 3]
o.n.a.s.SameDiff - Executing op reshape
**o.n.a.s.SameDiff -  Input shape for mmul_1 is  [4, 3] Output shape for x-grad is  [4, 3]
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute. Please see above message (printed out from c++) for a possible cause of error.**

Notice here ^  Reproducible with: 
https://github.com/deeplearning4j/nd4j/blob/5318ffe87dd034af1e3c6a4d944c80d366d406f1/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/samediff/SameDiffTests.java#L911

java.lang.RuntimeException: Unknown exception.

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpDouble(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1565)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4119)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:3574)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:3691)
	at org.nd4j.autodiff.samediff.SameDiffTests.testSoftmaxRegression(SameDiffTests.java:907)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by raver119** [comment]
Sorry, my bad. Documentation issue.

First integer argument should be order.

**Comment by raver119** [comment]
Fixed, afaik
