### ISSUE TITLE
ND4J on Raspberry PI3

### ISSUE THREAD

**Issue by kamir** [deeplearning4j/libnd4j#700]
I tried to implement image classification on a Raspberry PI3. 

./image_classification.sh 

java version "1.8.0_65"

Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/pi/Documents/dl4j-examples/bin/dl4j_examples_jar/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/pi/Documents/dl4j-examples/bin/dl4j_examples_jar/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
o.d.z.ZooModel - Using cached model at /home/pi/.deeplearning4j/vgg16_dl4j_inference.zip
o.d.z.ZooModel - Verifying download...
o.d.z.ZooModel - Checksum local is 3501732770, expecting 3501732770
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend

_Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:411)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:362)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:88)
	at org.deeplearning4j.betterfit.vgg16.CustomModelPrediction.loadModels(CustomModelPrediction.java:118)
	at org.deeplearning4j.PIImageClassifierTool.main(PIImageClassifierTool.java:27)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 14 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:63)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
	... 15 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)_

**Comment by kamir** [comment]
Following the recommendations in this issue: #243 
leads to a different issue:

sudo apt-get update && sudo apt-get upgrade


./buildnativeoperations.sh -o linux-armhf
eval cmake
PACKAGING = none
BUILD = release
CHIP = cpu
ARCH = armv7-r
CHIP_EXTENSION = 
CHIP_VERSION = 
GPU_COMPUTE_CAPABILITY = all
EXPERIMENTAL = no
LIBRARY TYPE = dynamic
/home/pi/Documents/libnd4j/blasbuild/cpu
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.8 or higher is required.  You are running version 3.7.2


-- Configuring incomplete, errors occurred!


What would be the right approach to build the nd4j libraries on the PI3 ?

**Comment by kamir** [comment]
Installing CMake 3.8.1 using those commands:



wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz
tar -xvzf cmake-3.8.1.tar.gz
cd cmake-3.8.1
sudo ./bootstrap
sudo make
sudo make install



worked fine.

But, compiling ND4J still fails:

eval cmake
PACKAGING = none
BUILD = release
CHIP = cpu
ARCH = armv7-r
CHIP_EXTENSION = 
CHIP_VERSION = 
GPU_COMPUTE_CAPABILITY = all
EXPERIMENTAL = no
LIBRARY TYPE = dynamic
/home/pi/Documents/libnd4j/blasbuild/cpu
CMake Error at /usr/local/share/cmake-3.8/Modules/CMakeDetermineSystem.cmake:94 (message):
  Could not find toolchain file: /home/pi/raspberrypi/pi.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by saudet** [comment]
Please try to follow the instructions here:
https://github.com/deeplearning4j/libnd4j/blob/master/RaspberryPi2.md

**Comment by rvanderwerf** [comment]
I'm having build problems here,I opened 2829 and they said to add it here is what I am seeing. Looking forward to getting past this so I can get to building!

Please describe your issue, along with:
following the guide to compile for the PI I am getting the following error while running: ./buildnativeoperations.sh -o linux-armhf

I get the following error. I made sure when cross compiling I am using the $ENV{HOME}/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc in pi.cmake or the local version on the pi itself but I get the same error. If I open that link.txt file to remove the -lFALSE it just regenerates it when running it again.

[100%] Linking CXX shared library libnd4j.so
cd /home/pi/github/libnd4j/blasbuild/cpu/blas && /usr/bin/cmake -E cmake_link_script CMakeFiles/nd4j.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-g++ -fPIC -Wall -O3 -Wl,-rpath,$ORIGIN/ -march=armv7-r -fopenmp -Wall -O3 -std=c++11 -fassociative-math -funsafe-math-optimizations -shared -Wl,-soname,libnd4j.so -o libnd4j.so CMakeFiles/nd4j.dir/cpu/NativeBlas.cpp.o CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o -lFALSE
/usr/bin/ld: cannot find -lFALSE
collect2: error: ld returned 1 exit status
blas/CMakeFiles/nd4j.dir/build.make:123: recipe for target 'blas/libnd4j.so' failed

Version Information
latest github repo as if 9-12-15
Please indicate relevant versions, including, if relevant:

Deeplearning4j version - latest github master
platform information (OS, etc): 4.9.35-v7+ #1014 SMP
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
CUDA version, if used
NVIDIA driver version, if in use
also on cross compile machine getting same error:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"

**Comment by rvanderwerf** [comment]
I would love to get working on this, can someone point me to a pre-built binary for PI3 for Raspbian 8? At least so I can move forward! thx

**Comment by saudet** [comment]
@dschowta Could you update the build you contributed to make it work on Raspberry Pi?

**Comment by rvanderwerf** [comment]
any updates? I see the tag is remove but nothing updated yet?

**Comment by saudet** [comment]
No, not really, @raver119 ?

**Comment by kwatters** [comment]
I am going through the process of cross compiling for the raspi for the 1.0.0-alpha release.  I finally got to build success for nd4j and have a new set of jars that are compiled.  I have yet to validate that they work, beyond not seeing the unsatisfied link error.  

A few things I noticed.

1. you can't build the released nd4j.tar.gz associated with the release tag due to it not being a .git repo and one of the submodules (jackson?) uses some maven git plugin. 
2. you need to make sure you update the pom.xml in the  nd4j-backend-impls directory so the linux-armhf-default profile points at the raspi cross compiler  located in the  tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf  (where you cloned the cross compiler tools for raspi too.)
3. for some reason with mvn 3.3.9 didn't seem to obey the -pl '!:nd4j-cuda...'  property, so I ended up commenting those out as submodules in the nd4j-backend-impls pom...

otherwise, the instructions that were checked in , were super helpful!   

it's a bit late now, but I wanted to chime in and share some comments about my progress.

**Comment by saudet** [comment]
@kwatters Awesome! Please send pull requests so we can merge your changes and eventually integrate the build to the CI server.

And to answer your questions:
1. It works if we use Git to checkout the source code :) Obviously, we shouldn't have to do that, but I don't think it matters a great deal in practice?
2. We can set the property on the command line `mvn -Djavacpp.platform.root=...`
3. We have to use the same version of CUDA that the modules are currently changed to, so probably `-pl '!:nd4j-cuda-9.1,!:nd4j-cuda-9.1-platform,!:nd4j-tests'` by default these days

**Comment by rvanderwerf** [comment]
Great news, looking forward to trying it out! Keep us updated and thanks!

**Comment by kwatters** [comment]
Thanks for the guidance @saudet,  I think the problem is less an issue with what's checked in, it's more an issue with getting your cross compile environment setup as expected.  

I appear to successfully be training the Minst example on a RasPI3 at the moment.  

It appears all that is needed is the following 2 artifacts:

nd4j-native-1.0.0-alpha-linux-armhf.jar
nd4j-native-platform-1.0.0-alpha-linux-armhf.jar

I'm eagerly waiting to see if it completes training, however, I do see the following warning message in the logs that I think I need to address first

Java HotSpot(TM) Client VM warning: You have loaded library /home/pi/.javacpp/cache/openblas-0.2.20-1.4.1-linux-armhf.jar/org/bytedeco/javacpp/linux-armhf/libopenblas.so.0 which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

I think perhaps there is some flag or configuration option that I might have missed when building libdn4j ?  Any thoughts?  Or is this something with the build of nd4j ?  (Sorry,  I don't usually spend much time in JNI land..)

**Comment by kwatters** [comment]
If anyone wants to help with testing,
http://repo.myrobotlab.org/artifactory/webapp/#/artifacts/browse/tree/General/myrobotlab/org/nd4j
Disclaimer:  These jars/dependencies should be used at your own risk!

**Comment by saudet** [comment]
Looks like we need to link OpenBLAS with `-z noexecstack` on that platform, so I'll be updating the build script for that. Thanks for reporting!
